#!/usr/bin/env bash

# this is the command line interface to flatrack. it should be coppied and executed from your dockerfiles directory.

cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export DOCKERFILES=$(pwd)
source flatrack-config.sh

source $FLATRACK/cmd.sh

cmd $@
